<?php

/**
 * @file
 * Primary module hooks for Drupal coding standards module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dcs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.dcs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal coding standards rules & guidelines') . '</p>';
    return $output;
  }
}
