ti_core.ti_config.*:
  type: config_entity
  label: Teachit Configuration Entity
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    configuration:
      type: string
    json_configuration:
      type: string
    optional_value1:
      type: string
    optional_value2:
      type: string
    description:
      type: string
