<?php

/**
 * @file
 * Contains drupal_bootcamp.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_bootcamp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_bootcamp module.
    case 'help.page.drupal_bootcamp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal Bootcamp 2022') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function drupal_bootcamp_theme() {
  return [
    'drupal_bootcamp' => [
      'render element' => 'children',
    ],
  ];
}




